apiVersion: v1
kind: Service
metadata:
  name: sample-php-service
  namespace: sample-php
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: sample-php